#!/bin/bash
## BEGIN INIT INFO
# Provides: httpd
# Default-Start: 3 4 5
# Default-Stop: 0 1 2 3 4 6
# Required-Start:
#              
## END INIT INFO

# chkconfig: 345 1 99

# Source function library.
. /etc/init.d/functions

HOMEDIRS="/home"
HTTPD=/usr/local/apache/bin/httpd

base=${0##*/}

start() {
    echo -n "Starting httpd"
    $HTTPD -k start
	return 0
}

stop() {
    echo -n "Stopping httpd"
    $HTTPD -k stop
}

restart(){
    echo -n "Restarting httpd"
    $HTTPD -k restart
}

status() {
	if [ -f "$LOCKFILE" ]; then 
	    echo "$base is running"
	else
	    echo "$base is stopped"
	fi
	exit 0
}

case "$1" in
    restart)
	start && success || failure
	;;

    start)
	start && success || failure
	echo
	;;

    stop)
	stop && success || failure
	echo
	;;

    status)
	status
	;;

    *)
	echo $"Usage: $0 {start|stop|status|restart}"
	exit 3
	;;
esac
